---
deployment:
  tasks:
    # Deploy only from the main branch for production environment
    - if [ "$(git rev-parse --abbrev-ref HEAD)" == "main" ]; then
        export DEPLOYPATH=/home/dotdashb/planning_tool;
      else
        export DEPLOYPATH=/home/dotdashb/planning_tool_dev;
      fi
    - /bin/cp -R transportvoice $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    
    # Install dependencies and build the client
    - cd $DEPLOYPATH/transportvoice
    - npm install --production
    - cd $DEPLOYPATH/transportvoice/client
    - npm install
    - npm run build
    
    # Set proper file permissions
    - chmod -R 755 $DEPLOYPATH
    - find $DEPLOYPATH -type f -exec chmod 644 {} \; 